#!/bin/bash

if [ $1 == "configure" ]; then
	
	chown -R xbian:xbian /home/xbian/.xbmc/addons/plugin.xbianconfig/

        find /home/xbian/.xbmc/addons/plugin.xbianconfig -iname \*.pyc | xargs -L1 rm -f > /dev/null 2>&1

fi