#!/bin/bash

. /var/lib/dpkg/info/xbian-update.functions

if [ $1 == "configure" ]; then

    chown -R xbian:xbian /usr/local/share/{xbmc,kodi}/addons/plugin.xbianconfig/

    find /usr/local/share/{xbmc,kodi}/addons/plugin.xbianconfig -iname \*.py[co] | xargs -L1 rm -f &>/dev/null

    for f in $(cat /tmp/files2check.list 2>/dev/null); do
        grep -q "$(md5sum /usr/local/share/kodi/addons/plugin.xbianconfig/$f)" /tmp/files2check.md5 || { kodi_sendmsg '#001'; break; }
    done
    rm -f /tmp/files2check.md5 /tmp/files2check.list

    patch_configxbmc
fi

exit 0
